import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    wfbSelectJson:[
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'滨江校区',
        grade:'初中一年级',
        Oprice:350,
        can:'否',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      }
    ]
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
