import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    wfbSelectJson:[
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'滨江校区',
        grade:'初中一年级',
        Oprice:350,
        can:'否',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城南校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      },
      {
        id:'BJKC-20190405',
        name:'初中一年级班级课程',
        xiaoQ:'城北校区',
        grade:'初中一年级',
        Oprice:350,
        can:'是',
        Pprice:300
      }
    ],
    jiaoShiXinXi:[
      {
        name:'王子',
        phone:'137...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'授课老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'公主',
        phone:'133...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'授课老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'少爷',
        phone:'155...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'王子',
        phone:'137...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'授课老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'公主',
        phone:'133...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'授课老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'少爷',
        phone:'155...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      }
      ,{
        name:'王子',
        phone:'137...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'授课老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'公主',
        phone:'133...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'授课老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'少爷',
        phone:'155...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'少爷',
        phone:'155...',
        idCard:'4306...',
        address:'八字门',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭大少',
        phone:'188...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭二少',
        phone:'177...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭三少',
        phone:'121...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭大少',
        phone:'188...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭二少',
        phone:'177...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭三少',
        phone:'121...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭大少',
        phone:'188...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭二少',
        phone:'177...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭三少',
        phone:'121...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭三少',
        phone:'121...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      },
      {
        name:'白石岭三少',
        phone:'121...',
        idCard:'4306...',
        address:'白石岭',
        logo:'',
        inCampus:'滨江校区',
        teacherType:'业务老师',
        period:'大学',
        course:'英语',
        info:'暂无'
      }
    ]
  },
  mutations: {
  },
  actions: {
  },
  modules: {
  }
})
